# Generated by Django 5.0.4 on 2024-04-30 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaDiem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='XeMay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('gia', models.IntegerField()),
                ('da_duoc_thue', models.BooleanField(default=False)),
                ('dang_hong', models.BooleanField(default=False)),
                ('dia_diem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds_xemay', to='rent.diadiem')),
            ],
        ),
        migrations.CreateModel(
            name='ThueXe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_thue', models.DateTimeField(auto_now_add=True)),
                ('ngay_tra', models.DateTimeField()),
                ('da_tra', models.BooleanField(default=False)),
                ('nguoi_thue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('xe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds_thue', to='rent.xemay')),
            ],
        ),
    ]
