# Generated by Django 5.0.4 on 2024-04-30 10:02

import django.db.models.deletion
import rent.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thuexe',
            name='dia_diem',
            field=models.ForeignKey(default=rent.models.get_default_dia_diem, on_delete=django.db.models.deletion.CASCADE, related_name='ds_thue', to='rent.diadiem'),
        ),
    ]
