# Generated by Django 5.0.4 on 2024-05-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_thuexe_dia_diem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xemay',
            name='ten',
            field=models.CharField(max_length=20),
        ),
    ]
