# Generated by Django 5.0.4 on 2024-05-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_xemay_loai_xe'),
    ]

    operations = [
        migrations.AddField(
            model_name='diadiem',
            name='dia_chi_cu_the',
            field=models.CharField(default='Test địa chỉ cụ thể', max_length=200),
        ),
        migrations.AlterField(
            model_name='diadiem',
            name='ten',
            field=models.CharField(max_length=20),
        ),
    ]
