# Generated by Django 5.0.4 on 2024-05-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0005_diadiem_dia_chi_cu_the_alter_diadiem_ten'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhuKien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('mota', models.TextField()),
                ('gia', models.IntegerField()),
            ],
        ),
    ]
