# Generated by Django 5.0.4 on 2024-05-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0007_thuexe_da_thanhtoan'),
    ]

    operations = [
        migrations.AddField(
            model_name='thuexe',
            name='diachi_nhanxe',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
