# Generated by Django 5.0.4 on 2024-05-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0008_thuexe_diachi_nhanxe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thuexe',
            name='ngay_thue',
            field=models.DateTimeField(),
        ),
    ]
