# Generated by Django 5.0.5 on 2024-05-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0009_alter_thuexe_ngay_thue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thuexe',
            name='ngay_thue',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='thuexe',
            name='ngay_tra',
            field=models.DateField(),
        ),
    ]
