# Generated by Django 5.0.6 on 2024-05-10 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0010_alter_thuexe_ngay_thue_alter_thuexe_ngay_tra'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ThueXe',
        ),
    ]
