# Generated by Django 5.0.6 on 2024-05-12 10:08

import django.db.models.deletion
import rent.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0011_delete_thuexe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_thue', models.DateField()),
                ('ngay_tra', models.DateField()),
                ('diachi_nhanxe', models.CharField(blank=True, max_length=100)),
                ('tong_tien', models.IntegerField()),
                ('dia_diem', models.ForeignKey(default=rent.models.get_default_dia_diem, on_delete=django.db.models.deletion.CASCADE, related_name='ds_order', to='rent.diadiem')),
                ('nguoi_thue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('xe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds_order', to='rent.xemay')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=128)),
                ('amount', models.CharField(blank=True, max_length=200, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='rent.order')),
            ],
        ),
    ]
