# Generated by Django 5.0.6 on 2024-05-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0012_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='address',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
