# Generated by Django 5.0.6 on 2024-05-13 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0013_alter_payment_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPhuKien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.order')),
                ('phu_kien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.phukien')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='phu_phi',
            field=models.ManyToManyField(blank=True, through='rent.OrderPhuKien', to='rent.phukien'),
        ),
    ]
