# Generated by Django 5.0.6 on 2024-05-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0015_order_is_baohiem_order_is_diduongdai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_baohiem',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_diduongdai',
        ),
        migrations.AddField(
            model_name='order',
            name='phi_baohiem',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='phi_diduongdai',
            field=models.IntegerField(default=0),
        ),
    ]
