# Generated by Django 5.0.6 on 2024-05-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0016_remove_order_is_baohiem_remove_order_is_diduongdai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bi_huy',
            field=models.BooleanField(default=False),
        ),
    ]
